/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as MeuPlanoRouteImport } from './routes/meu-plano'
import { Route as MedalhasRouteImport } from './routes/medalhas'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as GruposRouteImport } from './routes/grupos'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CronogramasRouteImport } from './routes/cronogramas'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GruposIdRouteImport } from './routes/grupos.$id'
import { Route as CronogramaIdRouteImport } from './routes/cronograma.$id'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe.webhook'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MeuPlanoRoute = MeuPlanoRouteImport.update({
  id: '/meu-plano',
  path: '/meu-plano',
  getParentRoute: () => rootRouteImport,
} as any)
const MedalhasRoute = MedalhasRouteImport.update({
  id: '/medalhas',
  path: '/medalhas',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const GruposRoute = GruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CronogramasRoute = CronogramasRouteImport.update({
  id: '/cronogramas',
  path: '/cronogramas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GruposIdRoute = GruposIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GruposRoute,
} as any)
const CronogramaIdRoute = CronogramaIdRouteImport.update({
  id: '/cronograma/$id',
  path: '/cronograma/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cronogramas': typeof CronogramasRoute
  '/dashboard': typeof DashboardRoute
  '/grupos': typeof GruposRouteWithChildren
  '/loja': typeof LojaRoute
  '/medalhas': typeof MedalhasRoute
  '/meu-plano': typeof MeuPlanoRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/cronograma/$id': typeof CronogramaIdRoute
  '/grupos/$id': typeof GruposIdRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cronogramas': typeof CronogramasRoute
  '/dashboard': typeof DashboardRoute
  '/grupos': typeof GruposRouteWithChildren
  '/loja': typeof LojaRoute
  '/medalhas': typeof MedalhasRoute
  '/meu-plano': typeof MeuPlanoRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/cronograma/$id': typeof CronogramaIdRoute
  '/grupos/$id': typeof GruposIdRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cronogramas': typeof CronogramasRoute
  '/dashboard': typeof DashboardRoute
  '/grupos': typeof GruposRouteWithChildren
  '/loja': typeof LojaRoute
  '/medalhas': typeof MedalhasRoute
  '/meu-plano': typeof MeuPlanoRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/cronograma/$id': typeof CronogramaIdRoute
  '/grupos/$id': typeof GruposIdRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/cronogramas'
    | '/dashboard'
    | '/grupos'
    | '/loja'
    | '/medalhas'
    | '/meu-plano'
    | '/perfil'
    | '/ranking'
    | '/cronograma/$id'
    | '/grupos/$id'
    | '/api/stripe/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/cronogramas'
    | '/dashboard'
    | '/grupos'
    | '/loja'
    | '/medalhas'
    | '/meu-plano'
    | '/perfil'
    | '/ranking'
    | '/cronograma/$id'
    | '/grupos/$id'
    | '/api/stripe/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/cronogramas'
    | '/dashboard'
    | '/grupos'
    | '/loja'
    | '/medalhas'
    | '/meu-plano'
    | '/perfil'
    | '/ranking'
    | '/cronograma/$id'
    | '/grupos/$id'
    | '/api/stripe/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CronogramasRoute: typeof CronogramasRoute
  DashboardRoute: typeof DashboardRoute
  GruposRoute: typeof GruposRouteWithChildren
  LojaRoute: typeof LojaRoute
  MedalhasRoute: typeof MedalhasRoute
  MeuPlanoRoute: typeof MeuPlanoRoute
  PerfilRoute: typeof PerfilRoute
  RankingRoute: typeof RankingRoute
  CronogramaIdRoute: typeof CronogramaIdRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meu-plano': {
      id: '/meu-plano'
      path: '/meu-plano'
      fullPath: '/meu-plano'
      preLoaderRoute: typeof MeuPlanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medalhas': {
      id: '/medalhas'
      path: '/medalhas'
      fullPath: '/medalhas'
      preLoaderRoute: typeof MedalhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grupos': {
      id: '/grupos'
      path: '/grupos'
      fullPath: '/grupos'
      preLoaderRoute: typeof GruposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cronogramas': {
      id: '/cronogramas'
      path: '/cronogramas'
      fullPath: '/cronogramas'
      preLoaderRoute: typeof CronogramasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grupos/$id': {
      id: '/grupos/$id'
      path: '/$id'
      fullPath: '/grupos/$id'
      preLoaderRoute: typeof GruposIdRouteImport
      parentRoute: typeof GruposRoute
    }
    '/cronograma/$id': {
      id: '/cronograma/$id'
      path: '/cronograma/$id'
      fullPath: '/cronograma/$id'
      preLoaderRoute: typeof CronogramaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GruposRouteChildren {
  GruposIdRoute: typeof GruposIdRoute
}

const GruposRouteChildren: GruposRouteChildren = {
  GruposIdRoute: GruposIdRoute,
}

const GruposRouteWithChildren =
  GruposRoute._addFileChildren(GruposRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CronogramasRoute: CronogramasRoute,
  DashboardRoute: DashboardRoute,
  GruposRoute: GruposRouteWithChildren,
  LojaRoute: LojaRoute,
  MedalhasRoute: MedalhasRoute,
  MeuPlanoRoute: MeuPlanoRoute,
  PerfilRoute: PerfilRoute,
  RankingRoute: RankingRoute,
  CronogramaIdRoute: CronogramaIdRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
