/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as MedalhasRouteImport } from './routes/medalhas'
import { Route as GruposRouteImport } from './routes/grupos'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CronogramasRouteImport } from './routes/cronogramas'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CronogramaIdRouteImport } from './routes/cronograma.$id'

const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const MedalhasRoute = MedalhasRouteImport.update({
  id: '/medalhas',
  path: '/medalhas',
  getParentRoute: () => rootRouteImport,
} as any)
const GruposRoute = GruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CronogramasRoute = CronogramasRouteImport.update({
  id: '/cronogramas',
  path: '/cronogramas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CronogramaIdRoute = CronogramaIdRouteImport.update({
  id: '/cronograma/$id',
  path: '/cronograma/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cronogramas': typeof CronogramasRoute
  '/dashboard': typeof DashboardRoute
  '/grupos': typeof GruposRoute
  '/medalhas': typeof MedalhasRoute
  '/ranking': typeof RankingRoute
  '/cronograma/$id': typeof CronogramaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cronogramas': typeof CronogramasRoute
  '/dashboard': typeof DashboardRoute
  '/grupos': typeof GruposRoute
  '/medalhas': typeof MedalhasRoute
  '/ranking': typeof RankingRoute
  '/cronograma/$id': typeof CronogramaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cronogramas': typeof CronogramasRoute
  '/dashboard': typeof DashboardRoute
  '/grupos': typeof GruposRoute
  '/medalhas': typeof MedalhasRoute
  '/ranking': typeof RankingRoute
  '/cronograma/$id': typeof CronogramaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/cronogramas'
    | '/dashboard'
    | '/grupos'
    | '/medalhas'
    | '/ranking'
    | '/cronograma/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/cronogramas'
    | '/dashboard'
    | '/grupos'
    | '/medalhas'
    | '/ranking'
    | '/cronograma/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/cronogramas'
    | '/dashboard'
    | '/grupos'
    | '/medalhas'
    | '/ranking'
    | '/cronograma/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CronogramasRoute: typeof CronogramasRoute
  DashboardRoute: typeof DashboardRoute
  GruposRoute: typeof GruposRoute
  MedalhasRoute: typeof MedalhasRoute
  RankingRoute: typeof RankingRoute
  CronogramaIdRoute: typeof CronogramaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medalhas': {
      id: '/medalhas'
      path: '/medalhas'
      fullPath: '/medalhas'
      preLoaderRoute: typeof MedalhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grupos': {
      id: '/grupos'
      path: '/grupos'
      fullPath: '/grupos'
      preLoaderRoute: typeof GruposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cronogramas': {
      id: '/cronogramas'
      path: '/cronogramas'
      fullPath: '/cronogramas'
      preLoaderRoute: typeof CronogramasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cronograma/$id': {
      id: '/cronograma/$id'
      path: '/cronograma/$id'
      fullPath: '/cronograma/$id'
      preLoaderRoute: typeof CronogramaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CronogramasRoute: CronogramasRoute,
  DashboardRoute: DashboardRoute,
  GruposRoute: GruposRoute,
  MedalhasRoute: MedalhasRoute,
  RankingRoute: RankingRoute,
  CronogramaIdRoute: CronogramaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
